easy_admin:
  entities:
    Student:
      class: App\Entity\Student
      form:
        fields:
          - "firstname"
          - "lastname"
          - {
              property: "promotion",
              type: "entity",
              type_options: { choice_label: "name" },
            }
    Promotion:
      class: App\Entity\Promotion
      form:
        fields:
          - "name"
          - "startDate"
          - "endDate"
          - {
              property: "students",
              type: "entity",
              type_options: { choice_label: "firstname", multiple: true },
            }
