<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQwJFf9k\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQwJFf9k/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerQwJFf9k.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerQwJFf9k\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerQwJFf9k\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'QwJFf9k',
    'container.build_id' => '7a4ae4e6',
    'container.build_time' => 1550571185,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQwJFf9k');
