<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIFH82x0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIFH82x0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIFH82x0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIFH82x0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIFH82x0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IFH82x0',
    'container.build_id' => '212ce0cd',
    'container.build_time' => 1550237870,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIFH82x0');
