<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTzx7eFD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTzx7eFD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTzx7eFD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTzx7eFD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTzx7eFD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Tzx7eFD',
    'container.build_id' => 'a71af9a0',
    'container.build_time' => 1550571127,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTzx7eFD');
